PACKAGE_NAME="honor-fmi-hwmon"
PACKAGE_VERSION="0.1.0"

BUILT_MODULE_NAME[0]="honor-fmi-hwmon"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/$kernelver/build"
